create table Category(
                         categoryName varchar(59) null,
                         categoryId int generated by default as identity not null,
                         constraint Category_pk
                             primary key (categoryId)
);

create unique index Category_categoryName_uindex on Category(categoryName);

create table Post(
                     image varchar null,
                     postId int generated by default as identity not null,
                     text varchar(300) null,
                     constraint Post_pk
                         primary key (postId)
);
create table ShopItem(
                         ShopItemId int generated by default as identity not null,
                         description varchar null,
                         header varchar null,
                         price float8 not null default 1,
                         CategoryId int null,
                         constraint PK_ShopItemId
                             primary key (ShopItemId),
                         constraint more_0
                             check ("price" > 0),
                         constraint ShopItem_Category_categoryId_fk
                             foreign key (CategoryId)
                                 references Category
);
create table Characteristic(
                               charId int generated by default as identity not null,
                               itemId int null,
                               charName varchar(350) null,
                               charContent varchar(350) null,
                               constraint PK_Characteristic
                                   primary key (charId),
                               constraint Fk_item_char
                                   foreign key (itemId)
                                       references ShopItem on delete cascade
);
create table ItemContent(
                            contentId int generated by default as identity not null,
                            itemId int null,
                            content varchar null,
                            constraint PK_ItemContent
                                primary key (contentId),
                            constraint Fk_item_content
                                foreign key (itemId)
                                    references ShopItem on delete cascade
);
create table UserShop(
                         userId int generated by default as identity not null,
                         login varchar(50) null,
                         password varchar(100) null,
                         phoneNumber int null,
                         email varchar(70) null,
                         rights int null default 2,
                         constraint PK_User
                             primary key (userId)
);
create table Cart(
                     cartId int generated by default as identity not null,
                     ItemId int null,
                     count int null,
                     userId int null,
                     constraint PK_cart
                         primary key (cartId),
                     constraint Fk_item
                         foreign key (ItemId)
                             references ShopItem on delete cascade,
                     constraint FK_user_Cart
                         foreign key (userId)
                             references UserShop
);
create unique index Cart_ItemId_uindex on Cart(ItemId);
create table ItemComment(
                            commentId int generated by default as identity not null,
                            itemId int null,
                            content varchar null,
                            userId int null,
                            constraint PK_ItemComment
                                primary key (commentId),
                            constraint Fk_item_comment
                                foreign key (itemId)
                                    references ShopItem on delete cascade,
                            constraint Fk_user_Comment
                                foreign key (userId)
                                    references UserShop
);
create table OrderShop(
                          orderId int generated by default as identity not null,
                          itemId int null,
                          userId int null,
                          status int null default 1,
                          startDate timestamp null,
                          count int null default 1,
                          constraint PK_ItemComment_order
                              primary key (orderId),
                          constraint Fk_item_order
                              foreign key (itemId)
                                  references ShopItem on delete cascade,
                          constraint OrderShop_UserShop_userId_fk
                              foreign key (userId)
                                  references UserShop
);
create table Rating(
                       ratingId int generated by default as identity not null,
                       ratingValue float8 null,
                       userId int null,
                       itemId int null,
                       constraint Rating_pk
                           primary key (ratingId),
                       constraint Rating_UserShop_userId_fk
                           foreign key (userId)
                               references UserShop on delete cascade,
                       constraint Rating_ShopItem_ShopItemId_fk
                           foreign key (itemId)
                               references ShopItem on delete cascade
);
create unique index UserShop_email_uindex on UserShop(email);
create table images(
                       content varchar null,
                       imageId int generated by default as identity not null,
                       constraint images_pk
                           primary key (imageId)
);
